building the first page
GSG-CF05/FoodApp-team10 pull request #10
Opened 2022-02-07 11:38 UTC by shamskhodary

2022-02-07 14:14 UTC, mo7mad4 commented on index.html
> +            />
adding number Such as +62 and down arrow

2022-02-08 11:03 UTC, mo7mad4 submitted a review, later dismissed
Good job Shams

2022-02-08 11:51 UTC, MarwaKHTanani approved these changes

2022-02-08 11:53 UTC, azzsal requested changes
Your branch has some conflicts with the main branch.

2022-02-08 19:28 UTC, azzsal approved these changes

2022-02-08 19:30 UTC, MarwaKHTanani commented on style.css
> +  height: 56px;
I guess you should add "justify-content: center;" here

2022-02-08 19:32 UTC, MarwaKHTanani commented on style.css
> +  margin: 90px 0px;
changing this to margin: 40px 0px; making it better

2022-02-08 19:40 UTC, MarwaKHTanani commented on style.css
> +  font-size: 16px;
edit this to font-size: 12px;

2022-02-08 19:41 UTC, MarwaKHTanani requested changes
edit

2022-02-08 19:57 UTC, ShbairAli approved these changes

2022-02-09 05:29 UTC, MarwaKHTanani approved these changes

2022-02-09 07:29 UTC, ShbairAli approved these changes

2022-02-09 09:57 UTC, mo7mad4 approved these changes

2022-02-09 10:41 UTC, ShbairAli approved these changes

2022-02-09 12:07 UTC, MarwaKHTanani approved these changes

2022-02-09 13:30 UTC, azzsal approved these changes

2022-02-09 14:15 UTC, merged