Create heading section and description
GSG-CF05/FoodApp-team10 pull request #13
Opened 2022-02-07 21:53 UTC by azzsal

Resolves #6

2022-02-08 17:21 UTC, shamskhodary approved these changes

2022-02-08 19:56 UTC, MarwaKHTanani commented on recipeDetail/recipeDetail.css
> +  color: #f00;
Just change the color to orange as shown in Figma

2022-02-08 19:57 UTC, MarwaKHTanani requested changes
edit

2022-02-08 20:19 UTC, shamskhodary reviewed
Good job

2022-02-08 20:20 UTC, ShbairAli approved these changes

2022-02-09 05:28 UTC, MarwaKHTanani approved these changes

2022-02-09 07:26 UTC, ShbairAli approved these changes

2022-02-09 09:51 UTC, mo7mad4 approved these changes

2022-02-09 09:52 UTC, merged